export const queryKeys = {
  departments: ['departments'] as const,
  csrActivities: ['csr', 'activities'] as const,
  csrParticipations: ['csr', 'participations'] as const,
  diversity: ['diversity'] as const,
  trainings: ['trainings'] as const,
  challenges: ['challenges'] as const,
  challengeParticipations: ['challenge-participations'] as const,
  challengeCounts: ['challenges', 'counts'] as const,
  leaderboard: (scope: string) => ['leaderboard', scope] as const,
  gameRewards: ['game-rewards'] as const,
  gameBadges: ['game-badges'] as const,
  categories: ['master', 'categories'] as const,
  carbon: ['carbon'] as const,
  goals: ['goals'] as const,
  carbonSummary: ['carbon-summary'] as const,
  governanceStats: ['governance', 'stats'] as const,
  governancePolicies: ['governance', 'policies'] as const,
  audits: ['audits'] as const,
  complianceIssues: ['compliance-issues'] as const,
  acknowledgements: ['acknowledgements'] as const,
  unacknowledged: ['policies', 'unacknowledged'] as const,
  notifications: ['notifications'] as const,
  employees: ['master', 'employees'] as const,
  scoresOverall: ['scores', 'overall'] as const,
  scoresDepartments: ['scores', 'departments'] as const,
  reports: ['reports'] as const,
}
