// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT count(*) FROM departments
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (id, name, code, head_id, parent_id, employee_count, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, code, head_id, parent_id, employee_count, status, created_at, updated_at
`

type CreateDepartmentParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Code          string      `json:"code"`
	HeadID        pgtype.UUID `json:"head_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	EmployeeCount int32       `json:"employee_count"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.HeadID,
		arg.ParentID,
		arg.EmployeeCount,
		arg.Status,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HeadID,
		&i.ParentID,
		&i.EmployeeCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDepartment = `-- name: DeactivateDepartment :one
UPDATE departments SET status='inactive', updated_at=now()
WHERE id=$1 RETURNING id, name, code, head_id, parent_id, employee_count, status, created_at, updated_at
`

func (q *Queries) DeactivateDepartment(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, deactivateDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HeadID,
		&i.ParentID,
		&i.EmployeeCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const departmentByID = `-- name: DepartmentByID :one
SELECT id, name, code, head_id, parent_id, employee_count, status, created_at, updated_at FROM departments WHERE id = $1
`

func (q *Queries) DepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, departmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HeadID,
		&i.ParentID,
		&i.EmployeeCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const departmentCodeExists = `-- name: DepartmentCodeExists :one
SELECT EXISTS(SELECT 1 FROM departments WHERE code = $1 AND id <> $2)
`

type DepartmentCodeExistsParams struct {
	Code string      `json:"code"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) DepartmentCodeExists(ctx context.Context, arg DepartmentCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, departmentCodeExists, arg.Code, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const eligibleDepartmentHead = `-- name: EligibleDepartmentHead :one
SELECT EXISTS(SELECT 1 FROM users WHERE id=$1 AND role IN ('dept_head','admin'))
`

func (q *Queries) EligibleDepartmentHead(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eligibleDepartmentHead, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, code, head_id, parent_id, employee_count, status, created_at, updated_at FROM departments ORDER BY name LIMIT $1 OFFSET $2
`

type ListDepartmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.HeadID,
			&i.ParentID,
			&i.EmployeeCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET name=$2, code=$3, head_id=$4, parent_id=$5,
  employee_count=$6, status=$7, updated_at=now()
WHERE id=$1 RETURNING id, name, code, head_id, parent_id, employee_count, status, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Code          string      `json:"code"`
	HeadID        pgtype.UUID `json:"head_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	EmployeeCount int32       `json:"employee_count"`
	Status        string      `json:"status"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.HeadID,
		arg.ParentID,
		arg.EmployeeCount,
		arg.Status,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HeadID,
		&i.ParentID,
		&i.EmployeeCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
