// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environmental.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeEmissionFactor = `-- name: ActiveEmissionFactor :one
SELECT unit,kgco2_per_unit,status FROM emission_factors WHERE id=$1
`

type ActiveEmissionFactorRow struct {
	Unit         string         `json:"unit"`
	Kgco2PerUnit pgtype.Numeric `json:"kgco2_per_unit"`
	Status       string         `json:"status"`
}

func (q *Queries) ActiveEmissionFactor(ctx context.Context, id pgtype.UUID) (ActiveEmissionFactorRow, error) {
	row := q.db.QueryRow(ctx, activeEmissionFactor, id)
	var i ActiveEmissionFactorRow
	err := row.Scan(&i.Unit, &i.Kgco2PerUnit, &i.Status)
	return i, err
}

const carbonSummary = `-- name: CarbonSummary :many
SELECT source, COALESCE(sum(computed_co2),0)::numeric(14,3) AS co2
FROM carbon_transactions
WHERE status='verified' AND ($1::uuid IS NULL OR department_id=$1) AND txn_date BETWEEN $2 AND $3
GROUP BY source ORDER BY source
`

type CarbonSummaryParams struct {
	Column1   pgtype.UUID `json:"column_1"`
	TxnDate   pgtype.Date `json:"txn_date"`
	TxnDate_2 pgtype.Date `json:"txn_date_2"`
}

type CarbonSummaryRow struct {
	Source string         `json:"source"`
	Co2    pgtype.Numeric `json:"co2"`
}

func (q *Queries) CarbonSummary(ctx context.Context, arg CarbonSummaryParams) ([]CarbonSummaryRow, error) {
	rows, err := q.db.Query(ctx, carbonSummary, arg.Column1, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarbonSummaryRow{}
	for rows.Next() {
		var i CarbonSummaryRow
		if err := rows.Scan(&i.Source, &i.Co2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonTransactionByID = `-- name: CarbonTransactionByID :one
SELECT id, department_id, source, quantity, emission_factor_id, factor_value, computed_co2, txn_date, evidence_url, status, verified_by, verified_at, created_at FROM carbon_transactions WHERE id=$1
`

func (q *Queries) CarbonTransactionByID(ctx context.Context, id pgtype.UUID) (CarbonTransaction, error) {
	row := q.db.QueryRow(ctx, carbonTransactionByID, id)
	var i CarbonTransaction
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Source,
		&i.Quantity,
		&i.EmissionFactorID,
		&i.FactorValue,
		&i.ComputedCo2,
		&i.TxnDate,
		&i.EvidenceUrl,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countCarbonTransactions = `-- name: CountCarbonTransactions :one
SELECT count(*) FROM carbon_transactions
WHERE ($1::uuid IS NULL OR department_id=$1)
  AND ($2::date IS NULL OR txn_date >= $2)
  AND ($3::date IS NULL OR txn_date <= $3)
  AND ($4::text = '' OR source=$4)
  AND ($5::text = '' OR status=$5)
`

type CountCarbonTransactionsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 string      `json:"column_5"`
}

func (q *Queries) CountCarbonTransactions(ctx context.Context, arg CountCarbonTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCarbonTransactions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvironmentalGoals = `-- name: CountEnvironmentalGoals :one
SELECT count(*) FROM environmental_goals WHERE ($1::uuid IS NULL OR department_id=$1)
`

func (q *Queries) CountEnvironmentalGoals(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentalGoals, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCarbonTransaction = `-- name: CreateCarbonTransaction :one
INSERT INTO carbon_transactions(id,department_id,source,quantity,emission_factor_id,factor_value,computed_co2,txn_date,evidence_url,status,created_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, department_id, source, quantity, emission_factor_id, factor_value, computed_co2, txn_date, evidence_url, status, verified_by, verified_at, created_at
`

type CreateCarbonTransactionParams struct {
	ID               pgtype.UUID        `json:"id"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	Source           string             `json:"source"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	EmissionFactorID pgtype.UUID        `json:"emission_factor_id"`
	FactorValue      pgtype.Numeric     `json:"factor_value"`
	ComputedCo2      pgtype.Numeric     `json:"computed_co2"`
	TxnDate          pgtype.Date        `json:"txn_date"`
	EvidenceUrl      pgtype.Text        `json:"evidence_url"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCarbonTransaction(ctx context.Context, arg CreateCarbonTransactionParams) (CarbonTransaction, error) {
	row := q.db.QueryRow(ctx, createCarbonTransaction,
		arg.ID,
		arg.DepartmentID,
		arg.Source,
		arg.Quantity,
		arg.EmissionFactorID,
		arg.FactorValue,
		arg.ComputedCo2,
		arg.TxnDate,
		arg.EvidenceUrl,
		arg.Status,
		arg.CreatedAt,
	)
	var i CarbonTransaction
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Source,
		&i.Quantity,
		&i.EmissionFactorID,
		&i.FactorValue,
		&i.ComputedCo2,
		&i.TxnDate,
		&i.EvidenceUrl,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEnvironmentalGoal = `-- name: CreateEnvironmentalGoal :one
INSERT INTO environmental_goals(id,name,department_id,target_co2,current_co2,deadline,status,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, name, department_id, target_co2, current_co2, deadline, status, created_at, updated_at
`

type CreateEnvironmentalGoalParams struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	TargetCo2    pgtype.Numeric     `json:"target_co2"`
	CurrentCo2   pgtype.Numeric     `json:"current_co2"`
	Deadline     pgtype.Date        `json:"deadline"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEnvironmentalGoal(ctx context.Context, arg CreateEnvironmentalGoalParams) (EnvironmentalGoal, error) {
	row := q.db.QueryRow(ctx, createEnvironmentalGoal,
		arg.ID,
		arg.Name,
		arg.DepartmentID,
		arg.TargetCo2,
		arg.CurrentCo2,
		arg.Deadline,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EnvironmentalGoal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DepartmentID,
		&i.TargetCo2,
		&i.CurrentCo2,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const departmentExists = `-- name: DepartmentExists :one
SELECT EXISTS(SELECT 1 FROM departments WHERE id=$1 AND status='active')
`

func (q *Queries) DepartmentExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, departmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const environmentalGoalByID = `-- name: EnvironmentalGoalByID :one
SELECT id, name, department_id, target_co2, current_co2, deadline, status, created_at, updated_at FROM environmental_goals WHERE id=$1
`

func (q *Queries) EnvironmentalGoalByID(ctx context.Context, id pgtype.UUID) (EnvironmentalGoal, error) {
	row := q.db.QueryRow(ctx, environmentalGoalByID, id)
	var i EnvironmentalGoal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DepartmentID,
		&i.TargetCo2,
		&i.CurrentCo2,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const goalsForDepartment = `-- name: GoalsForDepartment :many
SELECT id, name, department_id, target_co2, current_co2, deadline, status, created_at, updated_at FROM environmental_goals WHERE department_id=$1 ORDER BY deadline
`

func (q *Queries) GoalsForDepartment(ctx context.Context, departmentID pgtype.UUID) ([]EnvironmentalGoal, error) {
	rows, err := q.db.Query(ctx, goalsForDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentalGoal{}
	for rows.Next() {
		var i EnvironmentalGoal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DepartmentID,
			&i.TargetCo2,
			&i.CurrentCo2,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isDepartmentHead = `-- name: IsDepartmentHead :one
SELECT EXISTS(SELECT 1 FROM departments WHERE id=$1 AND head_id=$2 AND status='active')
`

type IsDepartmentHeadParams struct {
	ID     pgtype.UUID `json:"id"`
	HeadID pgtype.UUID `json:"head_id"`
}

func (q *Queries) IsDepartmentHead(ctx context.Context, arg IsDepartmentHeadParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDepartmentHead, arg.ID, arg.HeadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCarbonTransactions = `-- name: ListCarbonTransactions :many
SELECT id, department_id, source, quantity, emission_factor_id, factor_value, computed_co2, txn_date, evidence_url, status, verified_by, verified_at, created_at FROM carbon_transactions
WHERE ($1::uuid IS NULL OR department_id=$1)
  AND ($2::date IS NULL OR txn_date >= $2)
  AND ($3::date IS NULL OR txn_date <= $3)
  AND ($4::text = '' OR source=$4)
  AND ($5::text = '' OR status=$5)
ORDER BY txn_date DESC, created_at DESC LIMIT $6 OFFSET $7
`

type ListCarbonTransactionsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 string      `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListCarbonTransactions(ctx context.Context, arg ListCarbonTransactionsParams) ([]CarbonTransaction, error) {
	rows, err := q.db.Query(ctx, listCarbonTransactions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarbonTransaction{}
	for rows.Next() {
		var i CarbonTransaction
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Source,
			&i.Quantity,
			&i.EmissionFactorID,
			&i.FactorValue,
			&i.ComputedCo2,
			&i.TxnDate,
			&i.EvidenceUrl,
			&i.Status,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentalGoals = `-- name: ListEnvironmentalGoals :many
SELECT id, name, department_id, target_co2, current_co2, deadline, status, created_at, updated_at FROM environmental_goals WHERE ($1::uuid IS NULL OR department_id=$1)
ORDER BY deadline,name LIMIT $2 OFFSET $3
`

type ListEnvironmentalGoalsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListEnvironmentalGoals(ctx context.Context, arg ListEnvironmentalGoalsParams) ([]EnvironmentalGoal, error) {
	rows, err := q.db.Query(ctx, listEnvironmentalGoals, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentalGoal{}
	for rows.Next() {
		var i EnvironmentalGoal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DepartmentID,
			&i.TargetCo2,
			&i.CurrentCo2,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentalGoal = `-- name: UpdateEnvironmentalGoal :one
UPDATE environmental_goals SET name=$2,target_co2=$3,current_co2=$4,deadline=$5,status=$6,updated_at=$7
WHERE id=$1 RETURNING id, name, department_id, target_co2, current_co2, deadline, status, created_at, updated_at
`

type UpdateEnvironmentalGoalParams struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	TargetCo2  pgtype.Numeric     `json:"target_co2"`
	CurrentCo2 pgtype.Numeric     `json:"current_co2"`
	Deadline   pgtype.Date        `json:"deadline"`
	Status     string             `json:"status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEnvironmentalGoal(ctx context.Context, arg UpdateEnvironmentalGoalParams) (EnvironmentalGoal, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentalGoal,
		arg.ID,
		arg.Name,
		arg.TargetCo2,
		arg.CurrentCo2,
		arg.Deadline,
		arg.Status,
		arg.UpdatedAt,
	)
	var i EnvironmentalGoal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DepartmentID,
		&i.TargetCo2,
		&i.CurrentCo2,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifiedEmissionsThrough = `-- name: VerifiedEmissionsThrough :one
SELECT COALESCE(sum(computed_co2),0)::numeric(14,3) FROM carbon_transactions
WHERE status='verified' AND department_id=$1 AND txn_date <= $2
`

type VerifiedEmissionsThroughParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	TxnDate      pgtype.Date `json:"txn_date"`
}

func (q *Queries) VerifiedEmissionsThrough(ctx context.Context, arg VerifiedEmissionsThroughParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, verifiedEmissionsThrough, arg.DepartmentID, arg.TxnDate)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const verifyCarbonTransaction = `-- name: VerifyCarbonTransaction :one
UPDATE carbon_transactions SET computed_co2=$2,status='verified',verified_by=$3,verified_at=$4
WHERE id=$1 AND status='draft' RETURNING id, department_id, source, quantity, emission_factor_id, factor_value, computed_co2, txn_date, evidence_url, status, verified_by, verified_at, created_at
`

type VerifyCarbonTransactionParams struct {
	ID          pgtype.UUID        `json:"id"`
	ComputedCo2 pgtype.Numeric     `json:"computed_co2"`
	VerifiedBy  pgtype.UUID        `json:"verified_by"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) VerifyCarbonTransaction(ctx context.Context, arg VerifyCarbonTransactionParams) (CarbonTransaction, error) {
	row := q.db.QueryRow(ctx, verifyCarbonTransaction,
		arg.ID,
		arg.ComputedCo2,
		arg.VerifiedBy,
		arg.VerifiedAt,
	)
	var i CarbonTransaction
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Source,
		&i.Quantity,
		&i.EmissionFactorID,
		&i.FactorValue,
		&i.ComputedCo2,
		&i.TxnDate,
		&i.EvidenceUrl,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
