// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masterdata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const badgeByID = `-- name: BadgeByID :one
SELECT id, name, description, icon, unlock_rule, created_at, updated_at FROM badges WHERE id=$1
`

func (q *Queries) BadgeByID(ctx context.Context, id pgtype.UUID) (Badge, error) {
	row := q.db.QueryRow(ctx, badgeByID, id)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.UnlockRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const categoryByID = `-- name: CategoryByID :one
SELECT id, name, type, status, created_at, updated_at FROM categories WHERE id=$1
`

func (q *Queries) CategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, categoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countBadges = `-- name: CountBadges :one
SELECT count(*) FROM badges
`

func (q *Queries) CountBadges(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBadges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories WHERE ($1::text='' OR type=$1)
`

func (q *Queries) CountCategories(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmissionFactors = `-- name: CountEmissionFactors :one
SELECT count(*) FROM emission_factors WHERE ($1::uuid IS NULL OR category_id=$1)
`

func (q *Queries) CountEmissionFactors(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmissionFactors, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM users
`

func (q *Queries) CountEmployees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPolicies = `-- name: CountPolicies :one
SELECT count(*) FROM esg_policies
`

func (q *Queries) CountPolicies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductProfiles = `-- name: CountProductProfiles :one
SELECT count(*) FROM product_esg_profiles
`

func (q *Queries) CountProductProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRewards = `-- name: CountRewards :one
SELECT count(*) FROM rewards
`

func (q *Queries) CountRewards(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRewards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges(id,name,description,icon,unlock_rule) VALUES($1,$2,$3,$4,$5) RETURNING id, name, description, icon, unlock_rule, created_at, updated_at
`

type CreateBadgeParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Icon        string      `json:"icon"`
	UnlockRule  []byte      `json:"unlock_rule"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, createBadge,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.UnlockRule,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.UnlockRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories(id,name,type,status) VALUES($1,$2,$3,$4) RETURNING id, name, type, status, created_at, updated_at
`

type CreateCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmissionFactor = `-- name: CreateEmissionFactor :one
INSERT INTO emission_factors(id,name,category_id,unit,kgco2_per_unit,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, name, category_id, unit, kgco2_per_unit, status, created_at, updated_at
`

type CreateEmissionFactorParams struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	CategoryID   pgtype.UUID    `json:"category_id"`
	Unit         string         `json:"unit"`
	Kgco2PerUnit pgtype.Numeric `json:"kgco2_per_unit"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateEmissionFactor(ctx context.Context, arg CreateEmissionFactorParams) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, createEmissionFactor,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Unit,
		arg.Kgco2PerUnit,
		arg.Status,
	)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Kgco2PerUnit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO esg_policies(id,title,body,version,effective_date) VALUES($1,$2,$3,$4,$5) RETURNING id, title, body, version, effective_date, created_at, updated_at
`

type CreatePolicyParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Body          string      `json:"body"`
	Version       int32       `json:"version"`
	EffectiveDate pgtype.Date `json:"effective_date"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (EsgPolicy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Version,
		arg.EffectiveDate,
	)
	var i EsgPolicy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Version,
		&i.EffectiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductProfile = `-- name: CreateProductProfile :one
INSERT INTO product_esg_profiles(id,product,attributes,emission_factor_id) VALUES($1,$2,$3,$4) RETURNING id, product, attributes, emission_factor_id, created_at, updated_at
`

type CreateProductProfileParams struct {
	ID               pgtype.UUID `json:"id"`
	Product          string      `json:"product"`
	Attributes       []byte      `json:"attributes"`
	EmissionFactorID pgtype.UUID `json:"emission_factor_id"`
}

func (q *Queries) CreateProductProfile(ctx context.Context, arg CreateProductProfileParams) (ProductEsgProfile, error) {
	row := q.db.QueryRow(ctx, createProductProfile,
		arg.ID,
		arg.Product,
		arg.Attributes,
		arg.EmissionFactorID,
	)
	var i ProductEsgProfile
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Attributes,
		&i.EmissionFactorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReward = `-- name: CreateReward :one
INSERT INTO rewards(id,name,description,points_required,stock,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, name, description, points_required, stock, status, created_at, updated_at
`

type CreateRewardParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	PointsRequired int32       `json:"points_required"`
	Stock          int32       `json:"stock"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, createReward,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PointsRequired,
		arg.Stock,
		arg.Status,
	)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PointsRequired,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateEmployee = `-- name: DeactivateEmployee :execrows
UPDATE users SET status='inactive',updated_at=now() WHERE id=$1
`

func (q *Queries) DeactivateEmployee(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateEmployee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBadge = `-- name: DeleteBadge :execrows
DELETE FROM badges WHERE id=$1
`

func (q *Queries) DeleteBadge(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBadge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id=$1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmissionFactor = `-- name: DeleteEmissionFactor :execrows
DELETE FROM emission_factors WHERE id=$1
`

func (q *Queries) DeleteEmissionFactor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmissionFactor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePolicy = `-- name: DeletePolicy :execrows
DELETE FROM esg_policies WHERE id=$1
`

func (q *Queries) DeletePolicy(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductProfile = `-- name: DeleteProductProfile :execrows
DELETE FROM product_esg_profiles WHERE id=$1
`

func (q *Queries) DeleteProductProfile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReward = `-- name: DeleteReward :execrows
DELETE FROM rewards WHERE id=$1
`

func (q *Queries) DeleteReward(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReward, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const emissionFactorByID = `-- name: EmissionFactorByID :one
SELECT id, name, category_id, unit, kgco2_per_unit, status, created_at, updated_at FROM emission_factors WHERE id=$1
`

func (q *Queries) EmissionFactorByID(ctx context.Context, id pgtype.UUID) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, emissionFactorByID, id)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Kgco2PerUnit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getESGConfig = `-- name: GetESGConfig :one
SELECT singleton, auto_emission_calc, require_csr_evidence, auto_award_badges, notify_compliance_email, weight_env, weight_social, weight_gov, updated_at FROM esg_config WHERE singleton=TRUE
`

func (q *Queries) GetESGConfig(ctx context.Context) (EsgConfig, error) {
	row := q.db.QueryRow(ctx, getESGConfig)
	var i EsgConfig
	err := row.Scan(
		&i.Singleton,
		&i.AutoEmissionCalc,
		&i.RequireCsrEvidence,
		&i.AutoAwardBadges,
		&i.NotifyComplianceEmail,
		&i.WeightEnv,
		&i.WeightSocial,
		&i.WeightGov,
		&i.UpdatedAt,
	)
	return i, err
}

const listBadges = `-- name: ListBadges :many
SELECT id, name, description, icon, unlock_rule, created_at, updated_at FROM badges ORDER BY name LIMIT $1 OFFSET $2
`

type ListBadgesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBadges(ctx context.Context, arg ListBadgesParams) ([]Badge, error) {
	rows, err := q.db.Query(ctx, listBadges, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Badge{}
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.UnlockRule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, status, created_at, updated_at FROM categories WHERE ($1::text='' OR type=$1) ORDER BY name LIMIT $2 OFFSET $3
`

type ListCategoriesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmissionFactors = `-- name: ListEmissionFactors :many
SELECT id, name, category_id, unit, kgco2_per_unit, status, created_at, updated_at FROM emission_factors WHERE ($1::uuid IS NULL OR category_id=$1) ORDER BY name LIMIT $2 OFFSET $3
`

type ListEmissionFactorsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListEmissionFactors(ctx context.Context, arg ListEmissionFactorsParams) ([]EmissionFactor, error) {
	rows, err := q.db.Query(ctx, listEmissionFactors, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmissionFactor{}
	for rows.Next() {
		var i EmissionFactor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Unit,
			&i.Kgco2PerUnit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, name, email, password_hash, role, department_id, created_at, updated_at, xp, points, completed_challenges, status FROM users ORDER BY name LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.DepartmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Xp,
			&i.Points,
			&i.CompletedChallenges,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT event_type, in_app_enabled, email_enabled, updated_at FROM notification_preferences ORDER BY event_type
`

func (q *Queries) ListNotificationPreferences(ctx context.Context) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.EventType,
			&i.InAppEnabled,
			&i.EmailEnabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, title, body, version, effective_date, created_at, updated_at FROM esg_policies ORDER BY title LIMIT $1 OFFSET $2
`

type ListPoliciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]EsgPolicy, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EsgPolicy{}
	for rows.Next() {
		var i EsgPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Version,
			&i.EffectiveDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductProfiles = `-- name: ListProductProfiles :many
SELECT id, product, attributes, emission_factor_id, created_at, updated_at FROM product_esg_profiles ORDER BY product LIMIT $1 OFFSET $2
`

type ListProductProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductProfiles(ctx context.Context, arg ListProductProfilesParams) ([]ProductEsgProfile, error) {
	rows, err := q.db.Query(ctx, listProductProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductEsgProfile{}
	for rows.Next() {
		var i ProductEsgProfile
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Attributes,
			&i.EmissionFactorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, name, description, points_required, stock, status, created_at, updated_at FROM rewards ORDER BY name LIMIT $1 OFFSET $2
`

type ListRewardsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]Reward, error) {
	rows, err := q.db.Query(ctx, listRewards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PointsRequired,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyByID = `-- name: PolicyByID :one
SELECT id, title, body, version, effective_date, created_at, updated_at FROM esg_policies WHERE id=$1
`

func (q *Queries) PolicyByID(ctx context.Context, id pgtype.UUID) (EsgPolicy, error) {
	row := q.db.QueryRow(ctx, policyByID, id)
	var i EsgPolicy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Version,
		&i.EffectiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const productProfileByID = `-- name: ProductProfileByID :one
SELECT id, product, attributes, emission_factor_id, created_at, updated_at FROM product_esg_profiles WHERE id=$1
`

func (q *Queries) ProductProfileByID(ctx context.Context, id pgtype.UUID) (ProductEsgProfile, error) {
	row := q.db.QueryRow(ctx, productProfileByID, id)
	var i ProductEsgProfile
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Attributes,
		&i.EmissionFactorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rewardByID = `-- name: RewardByID :one
SELECT id, name, description, points_required, stock, status, created_at, updated_at FROM rewards WHERE id=$1
`

func (q *Queries) RewardByID(ctx context.Context, id pgtype.UUID) (Reward, error) {
	row := q.db.QueryRow(ctx, rewardByID, id)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PointsRequired,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBadge = `-- name: UpdateBadge :one
UPDATE badges SET name=$2,description=$3,icon=$4,unlock_rule=$5,updated_at=now() WHERE id=$1 RETURNING id, name, description, icon, unlock_rule, created_at, updated_at
`

type UpdateBadgeParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Icon        string      `json:"icon"`
	UnlockRule  []byte      `json:"unlock_rule"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, updateBadge,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.UnlockRule,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.UnlockRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name=$2,type=$3,status=$4,updated_at=now() WHERE id=$1 RETURNING id, name, type, status, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateESGConfig = `-- name: UpdateESGConfig :one
UPDATE esg_config SET auto_emission_calc=$1,require_csr_evidence=$2,auto_award_badges=$3,
 notify_compliance_email=$4,weight_env=$5,weight_social=$6,weight_gov=$7,updated_at=now()
WHERE singleton=TRUE RETURNING singleton, auto_emission_calc, require_csr_evidence, auto_award_badges, notify_compliance_email, weight_env, weight_social, weight_gov, updated_at
`

type UpdateESGConfigParams struct {
	AutoEmissionCalc      bool  `json:"auto_emission_calc"`
	RequireCsrEvidence    bool  `json:"require_csr_evidence"`
	AutoAwardBadges       bool  `json:"auto_award_badges"`
	NotifyComplianceEmail bool  `json:"notify_compliance_email"`
	WeightEnv             int32 `json:"weight_env"`
	WeightSocial          int32 `json:"weight_social"`
	WeightGov             int32 `json:"weight_gov"`
}

func (q *Queries) UpdateESGConfig(ctx context.Context, arg UpdateESGConfigParams) (EsgConfig, error) {
	row := q.db.QueryRow(ctx, updateESGConfig,
		arg.AutoEmissionCalc,
		arg.RequireCsrEvidence,
		arg.AutoAwardBadges,
		arg.NotifyComplianceEmail,
		arg.WeightEnv,
		arg.WeightSocial,
		arg.WeightGov,
	)
	var i EsgConfig
	err := row.Scan(
		&i.Singleton,
		&i.AutoEmissionCalc,
		&i.RequireCsrEvidence,
		&i.AutoAwardBadges,
		&i.NotifyComplianceEmail,
		&i.WeightEnv,
		&i.WeightSocial,
		&i.WeightGov,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmissionFactor = `-- name: UpdateEmissionFactor :one
UPDATE emission_factors SET name=$2,category_id=$3,unit=$4,kgco2_per_unit=$5,status=$6,updated_at=now() WHERE id=$1 RETURNING id, name, category_id, unit, kgco2_per_unit, status, created_at, updated_at
`

type UpdateEmissionFactorParams struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	CategoryID   pgtype.UUID    `json:"category_id"`
	Unit         string         `json:"unit"`
	Kgco2PerUnit pgtype.Numeric `json:"kgco2_per_unit"`
	Status       string         `json:"status"`
}

func (q *Queries) UpdateEmissionFactor(ctx context.Context, arg UpdateEmissionFactorParams) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, updateEmissionFactor,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Unit,
		arg.Kgco2PerUnit,
		arg.Status,
	)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Kgco2PerUnit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE users SET name=$2,email=$3,role=$4,department_id=$5,status=$6,updated_at=now() WHERE id=$1 RETURNING id, name, email, password_hash, role, department_id, created_at, updated_at, xp, points, completed_challenges, status
`

type UpdateEmployeeParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Role         string      `json:"role"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.DepartmentID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xp,
		&i.Points,
		&i.CompletedChallenges,
		&i.Status,
	)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE esg_policies SET title=$2,body=$3,version=$4,effective_date=$5,updated_at=now() WHERE id=$1 RETURNING id, title, body, version, effective_date, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Body          string      `json:"body"`
	Version       int32       `json:"version"`
	EffectiveDate pgtype.Date `json:"effective_date"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (EsgPolicy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Version,
		arg.EffectiveDate,
	)
	var i EsgPolicy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Version,
		&i.EffectiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductProfile = `-- name: UpdateProductProfile :one
UPDATE product_esg_profiles SET product=$2,attributes=$3,emission_factor_id=$4,updated_at=now() WHERE id=$1 RETURNING id, product, attributes, emission_factor_id, created_at, updated_at
`

type UpdateProductProfileParams struct {
	ID               pgtype.UUID `json:"id"`
	Product          string      `json:"product"`
	Attributes       []byte      `json:"attributes"`
	EmissionFactorID pgtype.UUID `json:"emission_factor_id"`
}

func (q *Queries) UpdateProductProfile(ctx context.Context, arg UpdateProductProfileParams) (ProductEsgProfile, error) {
	row := q.db.QueryRow(ctx, updateProductProfile,
		arg.ID,
		arg.Product,
		arg.Attributes,
		arg.EmissionFactorID,
	)
	var i ProductEsgProfile
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Attributes,
		&i.EmissionFactorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReward = `-- name: UpdateReward :one
UPDATE rewards SET name=$2,description=$3,points_required=$4,stock=$5,status=$6,updated_at=now() WHERE id=$1 RETURNING id, name, description, points_required, stock, status, created_at, updated_at
`

type UpdateRewardParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	PointsRequired int32       `json:"points_required"`
	Stock          int32       `json:"stock"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateReward(ctx context.Context, arg UpdateRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, updateReward,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PointsRequired,
		arg.Stock,
		arg.Status,
	)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PointsRequired,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences(event_type,in_app_enabled,email_enabled) VALUES($1,$2,$3)
ON CONFLICT(event_type) DO UPDATE SET in_app_enabled=EXCLUDED.in_app_enabled,email_enabled=EXCLUDED.email_enabled,updated_at=now()
RETURNING event_type, in_app_enabled, email_enabled, updated_at
`

type UpsertNotificationPreferenceParams struct {
	EventType    string `json:"event_type"`
	InAppEnabled bool   `json:"in_app_enabled"`
	EmailEnabled bool   `json:"email_enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference, arg.EventType, arg.InAppEnabled, arg.EmailEnabled)
	var i NotificationPreference
	err := row.Scan(
		&i.EventType,
		&i.InAppEnabled,
		&i.EmailEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
