import { useEffect, useState, type FormEvent } from 'react'
import { Button, EmptyState } from '../../design/components'
import { RequestError } from '../../lib/apiClient'
import type { CarbonSource, EmissionFactor, EnvironmentalGoal, GoalStatus } from '../../lib/types'
import { co2Preview, useEnvironmentalVM } from './useEnvironmentalVM'

type Tab='transactions'|'goals'|'factors'|'products'
const sourceLabels:Record<CarbonSource,string>={purchase:'Purchase / Energy',manufacturing:'Manufacturing',expense:'Expense / Travel',fleet:'Fleet'}
const statusLabels:Record<GoalStatus,string>={on_track:'On track',at_risk:'At risk',completed:'Completed'}

export function EnvironmentalPage(){const vm=useEnvironmentalVM();const[tab,setTab]=useState<Tab>('goals');const[entry,setEntry]=useState(false);const[goal,setGoal]=useState(false);const total=Number(vm.summary?.total??0);return <main className="page environmental-page"><section className="content-card"><header className="page-head"><div><p className="eyebrow env-text">Environmental</p><h1>Emission Tracking &amp; Goals</h1><p className="muted">Carbon accounting · deterministic verification · sustainability targets</p></div><div className="environmental-actions">{vm.user?.role!=='auditor'&&<Button className="secondary" onClick={()=>setEntry(true)}>Log carbon data</Button>}{(vm.user?.role==='admin'||vm.user?.role==='dept_head')&&<Button className="primary" onClick={()=>setGoal(true)}>New goal</Button>}</div></header><div className="env-kpis"><KPI label="Verified emissions (YTD)" value={`${total.toLocaleString()} kg CO₂`}/><KPI label="Active goals" value={String(vm.goals.filter(v=>v.status!=='completed').length)}/><KPI label="Emission factors" value={String(vm.factors.length)}/><KPI label="Auto calculation" value="Enabled"/></div><div className="tabs" role="tablist">{([['factors','Emission Factors'],['products','Product ESG Profiles'],['transactions','Carbon Transactions'],['goals','Environmental Goals']] as [Tab,string][]).map(([id,label])=><button role="tab" aria-selected={tab===id} className={`tab ${tab===id?'active':''}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='transactions'&&<Transactions vm={vm}/>} {tab==='goals'&&<Goals goals={vm.goals} departments={vm.departments}/>} {tab==='factors'&&<Factors factors={vm.factors}/>} {tab==='products'&&<EmptyState><h3>Product ESG profiles are managed in Settings</h3><p className="muted">Environmental linkage remains available through master data.</p></EmptyState>}<SourceSummary summary={vm.summary?.bySource??{}}/>{entry&&<CarbonModal vm={vm} onClose={()=>{setEntry(false);vm.resetIngest()}}/>}{goal&&<GoalModal vm={vm} onClose={()=>setGoal(false)}/>}</section></main>}

function KPI({label,value}:{label:string;value:string}){return <article className="env-kpi"><span>{label}</span><strong>{value}</strong></article>}
function Transactions({vm}:{vm:ReturnType<typeof useEnvironmentalVM>}){if(vm.loading)return <div className="center-state">Loading transactions...</div>;if(!vm.transactions.length)return <EmptyState><h3>No carbon transactions yet</h3><p className="muted">Upload an operational document to create the first draft.</p></EmptyState>;return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Source</th><th>Quantity</th><th className="numeric">CO₂ (kg)</th><th>Status</th><th>Action</th></tr></thead><tbody>{vm.transactions.map(row=><tr key={row.id}><td>{row.txnDate.slice(0,10)}</td><td>{sourceLabels[row.source]}</td><td>{row.quantity}</td><td className="numeric"><strong>{row.status==='verified'?Number(row.computedCo2).toLocaleString():'Pending'}</strong></td><td><span className={`env-pill ${row.status}`}>{row.status}</span></td><td>{vm.user?.role==='dept_head'&&row.status==='draft'?<Button className="ghost" onClick={()=>void vm.verify(row.id)}>Verify</Button>:'—'}</td></tr>)}</tbody></table></div>}
function Goals({goals,departments}:{goals:EnvironmentalGoal[];departments:{id:string;name:string}[]}){if(!goals.length)return <EmptyState><h3>No environmental goals yet</h3><p className="muted">Department heads and admins can create reduction targets.</p></EmptyState>;return <div className="table-wrap"><table><thead><tr><th>Goal</th><th>Department</th><th>Target</th><th>Current</th><th>Progress</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{goals.map(row=>{const progress=Math.min(100,Number(row.targetCo2)/Math.max(Number(row.currentCo2),Number(row.targetCo2))*100);return <tr key={row.id}><td><strong>{row.name}</strong></td><td>{departments.find(v=>v.id===row.departmentId)?.name??'Department'}</td><td>{row.targetCo2} kg</td><td>{row.currentCo2} kg</td><td><div className="goal-progress" aria-label={`${progress.toFixed(0)} percent`}><span style={{width:`${progress}%`}}/></div></td><td>{row.deadline.slice(0,10)}</td><td><span className={`env-pill ${row.status}`}>{statusLabels[row.status]}</span></td></tr>})}</tbody></table></div>}
function Factors({factors}:{factors:EmissionFactor[]}){return <div className="table-wrap"><table><thead><tr><th>Factor</th><th>Unit</th><th className="numeric">kg CO₂ / unit</th><th>Status</th></tr></thead><tbody>{factors.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.unit}</td><td className="numeric">{row.kgCo2PerUnit}</td><td><span className="env-pill verified">Active</span></td></tr>)}</tbody></table></div>}
function SourceSummary({summary}:{summary:Partial<Record<CarbonSource,string>>}){const values=(Object.keys(sourceLabels) as CarbonSource[]).map(source=>[source,Number(summary[source]??0)] as const);const max=Math.max(...values.map(v=>v[1]),1);return <section className="source-card"><h2>Verified emissions by source</h2>{values.map(([source,value])=><div className="source-row" key={source}><span>{sourceLabels[source]}</span><div><i style={{width:`${value/max*100}%`}}/></div><strong>{value.toLocaleString()} kg</strong></div>)}</section>}

function CarbonModal({vm,onClose}:{vm:ReturnType<typeof useEnvironmentalVM>;onClose():void}){const[factorID,setFactorID]=useState('');const[quantity,setQuantity]=useState('');const[source,setSource]=useState<CarbonSource>('fleet');const factor=vm.factors.find(v=>v.id===factorID);const departmentID=vm.user?.role==='admin'?(vm.departments[0]?.id??''):(vm.user?.departmentId??'');async function upload(file?:File){if(file)await vm.ingestFile(file)}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!factor)return;await vm.createDraft({departmentId:departmentID,source,quantity,emissionFactorId:factor.id,unit:factor.unit,txnDate:new FormData(e.currentTarget).get('txnDate') as string,evidenceUrl:vm.suggestion?.evidenceUrl})}const suggested=vm.suggestion;useEffect(()=>{if(suggested?.quantity){setQuantity(String(suggested.quantity));if(['purchase','manufacturing','expense','fleet'].includes(suggested.source))setSource(suggested.source as CarbonSource)}},[suggested]);return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header className="modal-head"><h2>Log carbon data</h2><button className="close-button" onClick={onClose}>×</button></header><form className="modal-form" onSubmit={submit}><p className="hint">AI categorizes only. The server calculates quantity × snapshotted emission factor after department-head verification.</p><label>Operational document<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>void upload(e.target.files?.[0])}/></label><div className="field-row"><label>Source<select value={source} onChange={e=>setSource(e.target.value as CarbonSource)}>{Object.entries(sourceLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Emission factor<select required value={factorID} onChange={e=>setFactorID(e.target.value)}><option value="">Select factor</option>{vm.factors.map(v=><option value={v.id} key={v.id}>{v.name} · {v.unit}</option>)}</select></label></div><div className="field-row"><label>Quantity<input required min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Transaction date<input required name="txnDate" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label></div><div className="co2-preview"><span>Display-only CO₂ preview</span><strong>{co2Preview(quantity,factor?.kgCo2PerUnit??0)} kg</strong></div><Error error={vm.error}/><footer><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button className="primary" disabled={!factor||!quantity||vm.state==='uploading'||vm.state==='submitting'}>{vm.state==='submitting'?'Submitting...':'Submit for verification'}</Button></footer></form></section></div>}
function GoalModal({vm,onClose}:{vm:ReturnType<typeof useEnvironmentalVM>;onClose():void}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await vm.createGoal({name:String(f.get('name')),departmentId:String(f.get('departmentId')),targetCo2:String(f.get('targetCo2')),currentCo2:String(f.get('currentCo2')||'0'),deadline:String(f.get('deadline'))});onClose()}return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header className="modal-head"><h2>New environmental goal</h2><button className="close-button" onClick={onClose}>×</button></header><form className="modal-form" onSubmit={submit}><label>Goal name<input name="name" required/></label><label>Department<select name="departmentId" required defaultValue={vm.user?.departmentId??''}>{vm.departments.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-row"><label>Target CO₂ (kg)<input name="targetCo2" type="number" min="0.001" step="0.001" required/></label><label>Current CO₂ (kg)<input name="currentCo2" type="number" min="0" step="0.001" defaultValue="0"/></label></div><label>Deadline<input name="deadline" type="date" required/></label><Error error={vm.error}/><footer><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button className="primary">Create goal</Button></footer></form></section></div>}
function Error({error}:{error:unknown}){return error?<p className="form-error" role="alert">{error instanceof RequestError?error.body.message:'Unable to complete the request'}</p>:null}
